[package]
name = "myinit"
version = "0.1.0"
edition = "2024"

[dependencies]
nix = { version = "0.29.0", features = ["process", "mount"] }
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.8.20"
